package com.cleanergy.model;

public enum State {
  STARTMENU, DICE, ROLL, QUESTION, FACTCHECK, QUIZBORDER, QUIZ, FINALQUIZ, UPDATEMINIGAME, ANEMOMINIGAME, ANEMOMINIGAMESCORE, SONNENMINIGAME, TUTORIAL, WINNER, END, BREAK, BREAKSOLO;
}
